/*
 * generated by Xtext 2.10.0
 */
package fr.i3s.gciatto.snn2uta.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class NetworkDescriptionLanguageUiModule extends AbstractNetworkDescriptionLanguageUiModule {
}
