/*
 * generated by Xtext 2.10.0
 */
package fr.i3s.gciatto.snn2uta


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NetworkDescriptionLanguageStandaloneSetup extends NetworkDescriptionLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new NetworkDescriptionLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
