/*
 * generated by Xtext 2.10.0
 */
package fr.i3s.gciatto.snn2uta


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NetworkDescriptionLanguageRuntimeModule extends AbstractNetworkDescriptionLanguageRuntimeModule {
}
